kind: "Site"
apis:
  - "asset"
  - "com.enonic.app.hmdb:medusaProducts"
mappings:
  - controller: "/cms/pages/home/home.js"
    match: "type:'portal:site'"
  - controller: "/cms/pages/landing/landing.js"
    match: "type:'com.enonic.app.hmdb:landing-page'"
  - controller: "/cms/pages/product/product.js"
    match: "type:'com.enonic.app.hmdb:product-page'"
  - controller: "/cms/pages/collection/collection.js"
    match: "type:'com.enonic.app.hmdb:collection'"
  - controller: "/lib/preview.js"
    match: "type:'(?!media:).*'"
